// Games configuration
export const gamesConfig = {
  projects: [
    {
      title: "STRAY BOT",
      description: "最初にゲーム制作に取り組んだ作品です。ロボットの『マトン君』を導くパズルゲーム。友達に描いてもらい、今でもお気に入りなロボです。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/stray_bot",
      githubLink: "#",
      images: ["/game/strayBot.png"],
      date: "2022-10-27",
    },
    {
      title: "シカクリバーシ",
      description: "ZeF君(@ZeF_games)との共同制作。「丸みもマス目もないリバーシ」です、ぜひ遊んでみてください。東京ゲームダンジョン3に出展しました。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/shikaku_reversi",
      githubLink: "#",
      images: ["/game/shikakuReversi.png"],
      date: "2023-08-31",
    },
    {
      title: "こなつのえにっき",
      description: "けめるさん(@qemelly_ongaku)とunity1weekの練習としてつくった作品。はじめてイラスト側に回って共同制作した作品です。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/konatsu_enikki",
      githubLink: "#",
      images: ["/game/konatsu.png"],
      date: "2024-08-04",
    },
    {
      title: "TANK STRIKE!!",
      description: "RDAG(@paldynojosh)さんのTinyTankを使った3D作品です。タンクがかわいいので、ほのぼのした感じを目指しました。一発ネタです。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/tank_strike",
      githubLink: "#",
      images: ["/game/TankStrike.png"],
      date: "2024-10-01",
    },
    {
      title: "帰路",
      description: "けめるさん(@qemelly_ongaku)との共同制作。パネルで2色をひっくり返して、少女を正しいゴールへ導くパズルゲーム。今後も育てたい作品です。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/kaerimichi",
      githubLink: "#",
      images: ["/game/kiro.png"],
      date: "2024-08-18",
    },
    {
      title: "『Dear past diary, 』",
      description: "実家の勉強机をごそごそしながら、自分の日記を読み返してみるノベルゲームです。ぜひ遊んでみてください。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/dear_past_diary",
      githubLink: "#",
      images: ["/game/DearPastDiary.png"],
      date: "2024-04-01",
    },
    {
      title: "マトン君 記憶探しの旅",
      description: "サイコロを振ってマトン君を進める、タイムアタック式すごろく。進めば進むほど、記憶の解像度が上がっていきます。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/matons_memory_journey",
      githubLink: "#",
      images: ["/game/memory.png"],
      date: "2023-06-26",
    },
    {
      title: "チョコミントを崇めよ！",
      description: "「チョコミントを全世界に布教しよう！」なカルト風クッキークリッカーです。1週間でここまでイラストを描いてくれた友達に感謝。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/worship-chocomint",
      githubLink: "#",
      images: ["/game/chocomint.png"],
      date: "2024-08-15",
    },
    {
      title: "FULL TANK",
      description: "unity1week初参加の作品です。音楽に合わせてバケツを操作し、水をキャッチしながらネズミをブロック。マルチタスクな音ゲーを目指したかった。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/full_tank_by_kakusuke",
      githubLink: "#",
      images: ["/game/Fulltank.png"],
      date: "2022-09-11",
    },
    {
      title: "カンパニーRe:イノベーション",
      description: "Slay the SpireみたいなマップをGitツリーにできないか模索したゲームです。黒歴史です。",
      technologies: ["Unity", "C#"],
      liveLink: "https://unityroom.com/games/company-re-innovation",
      githubLink: "#",
      images: ["/game/Company.png"],
      date: "2023-01-01",
    },
  ],
};
